#!/usr/bin/env python3
"""
gen_world.py — build the factory-like Gazebo world for the navigation mission.

Layout (metres, x forward from the launch base):

    BASE(0,0)  ->  slalom obstacle course  ->  ROOM(32,0) scan  ->  return to BASE

      y
      |   [rack]        [rack]                +---------------+
      |            [rack]        [rack]       |               |
    --+---O--------------------------------   |     ROOM      |  <- scan here
      |  base                                 |   12 x 12 m   |
      |        [pillar]      [pillar]         +---------------+
                                              (open on the -x face)

The course is deliberately tight enough to require real lateral movement but
wide enough to fly at low speed: 3.0 m gaps against a 0.5 m airframe.

Usage:  python3 tools/gen_world.py --out worlds/factory.sdf
"""

import argparse

HEAD = """<?xml version="1.0" ?>
<!-- GENERATED by drone_sim/tools/gen_world.py - do not edit by hand. -->
<sdf version="1.9">
  <world name="factory">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>
    <gravity>0 0 -9.8</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type='adiabatic'/>
    <scene>
      <grid>false</grid>
      <ambient>0.5 0.5 0.5 1</ambient>
      <background>0.75 0.78 0.82 1</background>
      <shadows>true</shadows>
    </scene>

    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-contact-system"
            name="gz::sim::systems::Contact"/>
    <plugin filename="gz-sim-imu-system"
            name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-air-pressure-system"
            name="gz::sim::systems::AirPressure"/>
    <plugin filename="gz-sim-magnetometer-system"
            name="gz::sim::systems::Magnetometer"/>
    <plugin filename="gz-sim-navsat-system"
            name="gz::sim::systems::NavSat"/>
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <!-- Wind is applied per scenario over gz transport. -->
    <plugin filename="gz-sim-wind-effects-system"
            name="gz::sim::systems::WindEffects">
      <force_approximation_scaling_factor>1</force_approximation_scaling_factor>
    </plugin>

    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>37.4</latitude_deg>
      <longitude_deg>-122.1</longitude_deg>
      <elevation>0</elevation>
    </spherical_coordinates>

    <light name="sun" type="directional">
      <pose>0 0 100 0 0 0</pose>
      <cast_shadows>true</cast_shadows>
      <intensity>1</intensity>
      <direction>-0.3 0.2 -0.9</direction>
      <diffuse>0.95 0.95 0.95 1</diffuse>
      <specular>0.25 0.25 0.25 1</specular>
      <attenuation><range>1000</range><constant>1</constant>
        <linear>0</linear><quadratic>0</quadratic></attenuation>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry>
          <material>
            <ambient>0.35 0.36 0.38 1</ambient>
            <diffuse>0.45 0.46 0.48 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
        <enable_wind>true</enable_wind>
      </link>
    </model>
"""

BOX = """
    <model name="{name}">
      <static>true</static>
      <pose>{x} {y} {z} 0 0 0</pose>
      <link name="link">
{collision}        <visual name="visual">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
          <material>
            <ambient>{r} {g} {b} 1</ambient>
            <diffuse>{r2} {g2} {b2} 1</diffuse>
          </material>
        </visual>
      </link>
    </model>
"""

COLLISION = """        <collision name="collision">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
        </collision>
"""

TAIL = """
  </world>
</sdf>
"""


def box(name, x, y, z, sx, sy, sz, rgb=(0.45, 0.35, 0.2), collide=True):
    """collide=False makes the box visual-only — for floor markings, which a
    vehicle should be able to sit on top of without a collision body to fight."""
    r, g, b = rgb
    col = COLLISION.format(sx=sx, sy=sy, sz=sz) if collide else ""
    return BOX.format(name=name, x=x, y=y, z=z, sx=sx, sy=sy, sz=sz,
                      collision=col,
                      r=r * 0.7, g=g * 0.7, b=b * 0.7, r2=r, g2=g, b2=b)


# Obstacle course: alternating racks that force lateral movement, then pillars.
# Gap between a rack edge and the corridor centre is ~3 m; the airframe is 0.5 m.
RACKS = [
    # (x, y_centre, length_y)  — racks run across the corridor, offset alternately
    (8.0, 3.2, 5.0),
    (12.0, -3.2, 5.0),
    (16.0, 3.2, 5.0),
    (20.0, -3.2, 5.0),
]
PILLARS = [(10.0, 0.0), (14.0, 0.0), (18.0, 0.0), (22.0, 0.0)]

ROOM_CX, ROOM_CY, ROOM_HALF, ROOM_H = 32.0, 0.0, 6.0, 4.0
WALL_T = 0.3


def build():
    parts = [HEAD]

    # Launch base pad — a painted floor marking, so VISUAL ONLY. Giving it a
    # collision body makes the vehicle spawn against it and fight the ground on
    # takeoff: an early run burned 34 Wh at 2.4 kW over 88 s before breaking
    # free, which wrecked the mission energy accounting.
    parts.append(box("launch_base", 0, 0, 0.01, 2.4, 2.4, 0.02,
                     rgb=(0.15, 0.45, 0.75), collide=False))

    # storage racks
    for i, (x, y, ly) in enumerate(RACKS):
        parts.append(box(f"rack_{i}", x, y, 1.5, 0.8, ly, 3.0,
                         rgb=(0.55, 0.42, 0.25)))

    # narrow pillars on the centreline — these are what force the slalom
    for i, (x, y) in enumerate(PILLARS):
        parts.append(box(f"pillar_{i}", x, y, 2.0, 0.45, 0.45, 4.0,
                         rgb=(0.6, 0.6, 0.62)))

    # the room to be scanned: four walls, open on the -x face
    cx, cy, h, H = ROOM_CX, ROOM_CY, ROOM_HALF, ROOM_H
    parts.append(box("room_wall_far", cx + h, cy, H / 2, WALL_T, 2 * h, H,
                     rgb=(0.7, 0.7, 0.72)))
    parts.append(box("room_wall_left", cx, cy + h, H / 2, 2 * h, WALL_T, H,
                     rgb=(0.7, 0.7, 0.72)))
    parts.append(box("room_wall_right", cx, cy - h, H / 2, 2 * h, WALL_T, H,
                     rgb=(0.7, 0.7, 0.72)))
    # partial near wall, leaving a 4 m doorway on the centreline
    for sgn in (+1, -1):
        parts.append(box(f"room_wall_near_{'p' if sgn > 0 else 'm'}",
                         cx - h, cy + sgn * (h / 2 + 1.0), H / 2,
                         WALL_T, h - 2.0, H, rgb=(0.7, 0.7, 0.72)))

    # a few objects inside the room so a scan has something to map
    parts.append(box("room_crate_a", cx - 2.0, cy + 2.5, 0.75, 1.6, 1.6, 1.5,
                     rgb=(0.5, 0.38, 0.22)))
    parts.append(box("room_crate_b", cx + 2.5, cy - 2.0, 1.0, 2.0, 1.2, 2.0,
                     rgb=(0.5, 0.38, 0.22)))
    parts.append(box("room_machine", cx + 1.0, cy + 3.0, 1.1, 2.4, 1.8, 2.2,
                     rgb=(0.3, 0.45, 0.5)))

    parts.append(TAIL)
    return "".join(parts)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="worlds/factory.sdf")
    a = ap.parse_args()
    with open(a.out, "w") as f:
        f.write(build())
    print(f"wrote {a.out}")
    print(f"  racks: {len(RACKS)}  pillars: {len(PILLARS)}")
    print(f"  room centred at ({ROOM_CX}, {ROOM_CY}), "
          f"{2*ROOM_HALF} x {2*ROOM_HALF} m, {ROOM_H} m tall")
