#!/usr/bin/env python3
"""
gen_world.py — build the factory-like Gazebo world for the navigation mission.

Layout (metres, x forward from the launch base):

    BASE(0,0)  ->  slalom obstacle course  ->  ROOM(32,0) scan  ->  return to BASE

      y
      |   [rack]        [rack]                +---------------+
      |            [rack]        [rack]       |               |
    --+---O--------------------------------   |     ROOM      |  <- scan here
      |  base                                 |   12 x 12 m   |
      |        [pillar]      [pillar]         +---------------+
                                              (open on the -x face)

The course is deliberately tight enough to require real lateral movement but
wide enough to fly at low speed: 3.0 m gaps against a 0.5 m airframe.

Usage:  python3 tools/gen_world.py --out worlds/factory.sdf
"""

import argparse

HEAD = """<?xml version="1.0" ?>
<!-- GENERATED by drone_sim/tools/gen_world.py - do not edit by hand. -->
<sdf version="1.9">
  <world name="factory">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>
    <gravity>0 0 -9.8</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type='adiabatic'/>
    <scene>
      <grid>false</grid>
      <ambient>0.5 0.5 0.5 1</ambient>
      <background>0.75 0.78 0.82 1</background>
      <shadows>true</shadows>
    </scene>

    <!--
      IMPORTANT: in Gazebo, declaring ANY <plugin> in a world REPLACES the
      default system set rather than adding to it. PX4's stock worlds declare
      none, so they inherit the defaults; the moment this world declares one,
      it must declare them ALL.

      Getting this wrong is silent and confusing. A version of this file that
      declared only WindEffects lost Physics, SceneBroadcaster and Sensors. The
      world still loaded and still published /world/factory/clock, but the
      /world/factory/scene/info service never appeared, and PX4 sat printing
      "Waiting for Gazebo world..." until it timed out. There is no error
      message anywhere pointing at the cause.

      WindEffects is why this world declares plugins at all: PX4's stock worlds
      do not include it, and the wind scenarios need it.
    -->
    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-contact-system"
            name="gz::sim::systems::Contact"/>
    <plugin filename="gz-sim-imu-system"
            name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-air-pressure-system"
            name="gz::sim::systems::AirPressure"/>
    <plugin filename="gz-sim-magnetometer-system"
            name="gz::sim::systems::Magnetometer"/>
    <plugin filename="gz-sim-navsat-system"
            name="gz::sim::systems::NavSat"/>
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-wind-effects-system"
            name="gz::sim::systems::WindEffects">
      <force_approximation_scaling_factor>1</force_approximation_scaling_factor>
    </plugin>

    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>37.4</latitude_deg>
      <longitude_deg>-122.1</longitude_deg>
      <elevation>0</elevation>
    </spherical_coordinates>

    <light name="sun" type="directional">
      <pose>0 0 100 0 0 0</pose>
      <cast_shadows>true</cast_shadows>
      <intensity>1</intensity>
      <direction>-0.3 0.2 -0.9</direction>
      <diffuse>0.95 0.95 0.95 1</diffuse>
      <specular>0.25 0.25 0.25 1</specular>
      <attenuation><range>1000</range><constant>1</constant>
        <linear>0</linear><quadratic>0</quadratic></attenuation>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry>
          <material>
            <ambient>0.35 0.36 0.38 1</ambient>
            <diffuse>0.45 0.46 0.48 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
        <enable_wind>true</enable_wind>
      </link>
    </model>
"""

BOX = """
    <model name="{name}">
      <static>true</static>
      <pose>{x} {y} {z} 0 0 0</pose>
      <link name="link">
{collision}        <visual name="visual">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
          <material>
            <ambient>{r} {g} {b} 1</ambient>
            <diffuse>{r2} {g2} {b2} 1</diffuse>
          </material>
        </visual>
      </link>
    </model>
"""

COLLISION = """        <collision name="collision">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
        </collision>
"""

TAIL = """
  </world>
</sdf>
"""


def box(name, x, y, z, sx, sy, sz, rgb=(0.45, 0.35, 0.2), collide=True):
    """collide=False makes the box visual-only — for floor markings, which a
    vehicle should be able to sit on top of without a collision body to fight."""
    r, g, b = rgb
    col = COLLISION.format(sx=sx, sy=sy, sz=sz) if collide else ""
    return BOX.format(name=name, x=x, y=y, z=z, sx=sx, sy=sy, sz=sz,
                      collision=col,
                      r=r * 0.7, g=g * 0.7, b=b * 0.7, r2=r, g2=g, b2=b)


# --- Obstacle course -------------------------------------------------------
# A first attempt used racks standing off to the side of the flight path plus
# thin centreline pillars. Measurement showed nothing came within a metre of
# the airframe: a drone with no perception at all would have flown it. It
# tested waypoint following, not obstacle navigation.
#
# This version is a genuine slalom. The corridor is walled, and each gate is a
# full-height barrier across it with ONE gap, alternating side to side. There
# is no way through except the gap, and no way over it.
CORRIDOR_HALF = 6.0          # side walls at y = +/- 6
# The corridor starts AHEAD of the launch base, at x = 3. An attempt to extend
# it back to x = -4 so the base sat inside the walls made the aircraft collide
# repeatedly; the known-good geometry is this one, so it stays. The base being
# just outside the entrance is also physically sensible - a launch pad sits
# outside the work area, and the aircraft flies in.
CORRIDOR_X0, CORRIDOR_X1 = 3.0, 24.0
BARRIER_H = 4.0              # taller than the 2.5 m cruise altitude
GATE_GAP = 2.5               # gap width against a 0.5 m airframe
GATES = [                    # (x, gap centre y)
    (8.0, 2.4),
    (12.0, -2.4),
    (16.0, 2.4),
    (20.0, -2.4),
]

ROOM_CX, ROOM_CY, ROOM_HALF, ROOM_H = 32.0, 0.0, 6.0, 4.0
WALL_T = 0.3


def obstacle_list():
    """Every collidable box: (name, cx, cy, cz, sx, sy, sz).

    Exposed so tools/check_clearance.py measures against the SAME geometry the
    world is built from, rather than a second hand-maintained copy that can
    silently drift.
    """
    out = []
    h, t = BARRIER_H, 0.4
    # corridor side walls
    L = CORRIDOR_X1 - CORRIDOR_X0
    cx = (CORRIDOR_X0 + CORRIDOR_X1) / 2.0
    out.append(("corridor_wall_left", cx, CORRIDOR_HALF, h / 2, L, t, h))
    out.append(("corridor_wall_right", cx, -CORRIDOR_HALF, h / 2, L, t, h))
    # gates: a barrier across the corridor with one gap
    for i, (x, gy) in enumerate(GATES):
        lo, hi = gy - GATE_GAP / 2.0, gy + GATE_GAP / 2.0
        a_len = hi_len = 0.0
        # panel from the right wall up to the gap
        a_len = lo - (-CORRIDOR_HALF)
        if a_len > 0.1:
            out.append((f"gate{i}_lower", x, (-CORRIDOR_HALF + lo) / 2.0,
                        h / 2, t, a_len, h))
        # panel from the gap up to the left wall
        hi_len = CORRIDOR_HALF - hi
        if hi_len > 0.1:
            out.append((f"gate{i}_upper", x, (hi + CORRIDOR_HALF) / 2.0,
                        h / 2, t, hi_len, h))
    cx, cy, h, H = ROOM_CX, ROOM_CY, ROOM_HALF, ROOM_H
    out.append(("room_wall_far", cx + h, cy, H / 2, WALL_T, 2 * h, H))
    out.append(("room_wall_left", cx, cy + h, H / 2, 2 * h, WALL_T, H))
    out.append(("room_wall_right", cx, cy - h, H / 2, 2 * h, WALL_T, H))
    for sgn in (+1, -1):
        out.append((f"room_wall_near_{'p' if sgn > 0 else 'm'}",
                    cx - h, cy + sgn * (h / 2 + 1.0), H / 2,
                    WALL_T, h - 2.0, H))
    out.append(("room_crate_a", cx - 2.0, cy + 2.5, 0.75, 1.6, 1.6, 1.5))
    out.append(("room_crate_b", cx + 2.5, cy - 2.0, 1.0, 2.0, 1.2, 2.0))
    out.append(("room_machine", cx + 1.0, cy + 3.0, 1.1, 2.4, 1.8, 2.2))
    return out


def build():
    parts = [HEAD]

    # Launch base pad — a painted floor marking, so VISUAL ONLY. Giving it a
    # collision body makes the vehicle spawn against it and fight the ground on
    # takeoff: an early run burned 34 Wh at 2.4 kW over 88 s before breaking
    # free, which wrecked the mission energy accounting.
    parts.append(box("launch_base", 0, 0, 0.01, 2.4, 2.4, 0.02,
                     rgb=(0.15, 0.45, 0.75), collide=False))

    # corridor and gates — generated from obstacle_list() so the world and the
    # clearance checker can never describe different geometry
    palette = {"corridor": (0.55, 0.56, 0.58), "gate": (0.62, 0.45, 0.22)}
    for name, x, y, z, sx, sy, sz in obstacle_list():
        if name.startswith("corridor"):
            parts.append(box(name, x, y, z, sx, sy, sz, rgb=palette["corridor"]))
        elif name.startswith("gate"):
            parts.append(box(name, x, y, z, sx, sy, sz, rgb=palette["gate"]))

    # the room to be scanned: four walls, open on the -x face
    cx, cy, h, H = ROOM_CX, ROOM_CY, ROOM_HALF, ROOM_H
    parts.append(box("room_wall_far", cx + h, cy, H / 2, WALL_T, 2 * h, H,
                     rgb=(0.7, 0.7, 0.72)))
    parts.append(box("room_wall_left", cx, cy + h, H / 2, 2 * h, WALL_T, H,
                     rgb=(0.7, 0.7, 0.72)))
    parts.append(box("room_wall_right", cx, cy - h, H / 2, 2 * h, WALL_T, H,
                     rgb=(0.7, 0.7, 0.72)))
    # partial near wall, leaving a 4 m doorway on the centreline
    for sgn in (+1, -1):
        parts.append(box(f"room_wall_near_{'p' if sgn > 0 else 'm'}",
                         cx - h, cy + sgn * (h / 2 + 1.0), H / 2,
                         WALL_T, h - 2.0, H, rgb=(0.7, 0.7, 0.72)))

    # a few objects inside the room so a scan has something to map
    parts.append(box("room_crate_a", cx - 2.0, cy + 2.5, 0.75, 1.6, 1.6, 1.5,
                     rgb=(0.5, 0.38, 0.22)))
    parts.append(box("room_crate_b", cx + 2.5, cy - 2.0, 1.0, 2.0, 1.2, 2.0,
                     rgb=(0.5, 0.38, 0.22)))
    parts.append(box("room_machine", cx + 1.0, cy + 3.0, 1.1, 2.4, 1.8, 2.2,
                     rgb=(0.3, 0.45, 0.5)))

    parts.append(TAIL)
    return "".join(parts)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="worlds/factory.sdf")
    a = ap.parse_args()
    with open(a.out, "w") as f:
        f.write(build())
    print(f"wrote {a.out}")
    print(f"  corridor: y +/-{CORRIDOR_HALF} m, x {CORRIDOR_X0}-{CORRIDOR_X1} m")
    print(f"  gates: {len(GATES)}, {GATE_GAP} m gap each, "
          f"alternating y = {[g[1] for g in GATES]}")
    print(f"  room centred at ({ROOM_CX}, {ROOM_CY}), "
          f"{2*ROOM_HALF} x {2*ROOM_HALF} m, {ROOM_H} m tall")
